name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Check asciidoc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install asciidoc-base
    - run: asciidoc README.adoc

